GET http://localhost:5000/datawanita

###
GET http://localhost:5000/datawanita/1

###
POST http://localhost:5000/datawanita
Content-Type: application/json

{
    "nama_lengkap": "nama_lengkap",
    "nama_panggilan": "nama_panggilan",
    "nama_ayah": "nama_ayah",
    "nama_ibu": "nama_ibu",
    "instagram": "instagram",
    "twitter": "twitter",
    "foto_wanita": "foto_wanita",
    "id_pasangan": 1
}

###
PATCH http://localhost:5000/datawanita/1
Content-Type: application/json

{
    "nama_lengkap": "nama_lengkap",
    "nama_panggilan": "nama_panggilan",
    "nama_ayah": "nama_ayah",
    "nama_ibu": "nama_ibu",
    "instagram": "instagram",
    "twitter": "twitter",
    "foto_wanita": "foto_wanita",
    "id_pasangan": 1
}

###
DELETE  http://localhost:5000/datawanita/1