// get all users
GET http://localhost:5000/user/1

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "admin",
    "no_telp": "234567",
    "foto_profile": "admin",
    "role": "admin"
}

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "username": "user",
    "email": "user@gmail.com",
    "password": "user",
    "no_telp": "234567",
    "foto_profile": "user"
}

###
// get user

GET http://localhost:5000/user/742611

###
// update user
PATCH http://localhost:5000/user/742610
Content-Type: application/json

{
    "Nama_User": "laisd",
    "Email": "admn@gmail.com",
    "No_Telp": "981237236124",
    "Password": "12345",
    "confPassword": "12345",
    "Role": "admin"
}


###
//delete user
DELETE http://localhost:5000/user/1
