### 
//login admin

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}
### 
//login user

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "user"
}

###
//logout

DELETE  http://localhost:5000/logout

###
GET http://localhost:5000/me
