### 
//login user

POST http://localhost:5000/login
Content-Type: application/json

{
    "Email": "admn@gmail.com",
    "Password": "123456789"
}

###
// get users

GET http://localhost:5000/me


###
// gelogout all users

DELETE  http://localhost:5000/logout