export const tawaran = [
    // {
    //   id: 1,
    //   category: "",
    //   title: "trial",
    //   awal: "Rp 20.000",
    //   disc: "0%",
    //   akhir: "Rp 90.000",
    //   fitur: [
    //     "Unlimited Acara",
    //     "Amplop Digital",
    //     "Unlimited Ucapan",
    //     "Share Whatsapp",
    //     "Add To Calender",
    //     "Pilihan Template",
    //     "200 Tamu",
    //     "10 Backsound",
    //     "20 Galeri Foto",
    //     "Masa Aktif (+10 Acara)",
    //   ],
    // },
    {
      id: 2,
      category: "",
      title: "bronze",
      awal: "Rp 20.000",
      disc: "100%",
      akhir: "Rp 90.000",
      num: 90000,
      fitur: [
        "Unlimited Acara",
        "Amplop Digital",
        "Unlimited Ucapan",
        "Share Whatsapp",
        "Add To Calender",
        "Pilihan Template",
        "200 Tamu",
        "10 Backsound",
        "20 Galeri Foto",
        "Masa Aktif (+10 Acara)",
      ],
    },
    {
      id: 3,
      category: "popular",
      title: "silver",
      awal: "Rp 20.000",
      disc: "100%",
      akhir: "Rp 70.000",
      num: 70000,
      fitur: [
        "Unlimited Acara",
        "Amplop Digital",
        "Unlimited Ucapan",
        "Share Whatsapp",
        "Add To Calender",
        "Pilihan Template",
        "200 Tamu",
        "10 Backsound",
        "30 Galeri Foto",
        "Masa Aktif (custom)",
      ],
    },
    {
      id: 4,
      category: "exclusive",
      title: "gold",
      awal: "Rp 20.000",
      disc: "100%",
      akhir: "Rp 40.000",
      num: 40000,
      fitur: [
        "Unlimited Acara",
        "Amplop Digital",
        "Unlimited Ucapan",
        "Share Whatsapp",
        "Add To Calender",
        "Pilihan Template",
        "200 Tamu",
        "10 Backsound",
        "30 Galeri Foto",
        "Masa Aktif (custom)",
      ],
    },
  ];